source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

target 'CalendarUGCC' do

pod 'AFNetworking', '~> 2.0' # Core, without NSURLSession, compatible with iOS6
# pod 'AFNetworking/NSURLSession', '~> 2.0' # Add NSURLSession features, only compatible with iOS7

pod 'MBProgressHUD', '~> 0.8'

pod 'ActionSheetPicker-3.0', '~> 1.0.9'

pod 'Fabric'
pod 'Crashlytics'

pod 'Reachability', '~> 3.1'

pod 'GoogleAnalytics-iOS-SDK', '~> 3.0'

end

target 'TodayWidget' do

pod 'Fabric'
pod 'Crashlytics'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0'

end

