# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'Calendar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Calendar
  pod 'CoreStore', '~> 5.3.1'
  pod 'PromiseKit', '~> 6.8'
  pod 'JGProgressHUD'
  pod 'Siren'
  pod 'AwaitKit', '~> 5.1.0'
  pod 'UIColor_Hex_Swift', '~> 5.0.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'Firebase/Analytics'
  
  target 'CalendarTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'PromiseKit', '~> 6.8'
  end

  target 'CalendarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
